### ISSUE TITLE
environment setup issue

### ISSUE THREAD

**Issue by rupeshghimire111** [rana22/FirstBinderProject#2]
i've started for environment setup for this project but stuck on some error which shows 404 error code while running the project 

this is the error:

HTTP Status 404 -

type Status report

message

description The requested resource is not available.

Apache Tomcat/8.0.32

i've used tomcat 8,java 1.8 and postgres 9.5

**Comment by rana22** [comment]
Did you test if the tomcat server is working fine?

**Comment by rupeshghimire111** [comment]
yes it's working fine

**Comment by rupeshghimire111** [comment]
working fine now

there was some issue with the java build path 

make sure to have correct psql jar file on correct path
